/**
 * Canonical domain and workflow enums for OSM.
 * Conforms to docs/contracts/05-domain-contract.md and docs/contracts/06-api-contract.md.
 */

export enum EvaluationStatus {
  DRAFT = "DRAFT",
  IN_PROGRESS = "IN_PROGRESS",
  SUBMITTED = "SUBMITTED",
  FINALIZED = "FINALIZED",
}

export enum SignalSeverity {
  INFO = "INFO",
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum QualitySignalStatus {
  GENERATED = "GENERATED",
  REVIEWABLE = "REVIEWABLE",
  LINKED_TO_CASE = "LINKED_TO_CASE",
  UNDER_INVESTIGATION = "UNDER_INVESTIGATION",
  RESOLVED = "RESOLVED",
  DISMISSED = "DISMISSED",
}

export enum TriageCaseStatus {
  OPEN = "OPEN",
  ASSIGNED = "ASSIGNED",
  UNDER_REVIEW = "UNDER_REVIEW",
  RESOLVED = "RESOLVED",
  ESCALATED = "ESCALATED",
}

export enum ResolutionOutcome {
  CONFIRMED_VALID = "CONFIRMED_VALID",
  LEGITIMATE_VARIATION = "LEGITIMATE_VARIATION",
  CORRECTION_REQUIRED = "CORRECTION_REQUIRED",
  ESCALATED = "ESCALATED",
  DISMISSED = "DISMISSED",
}

export enum ActorType {
  USER = "USER",
  SYSTEM = "SYSTEM",
  DETECTOR = "DETECTOR",
  AI = "AI",
  INTEGRATION = "INTEGRATION",
}

export enum UserRole {
  EXAMINER = "EXAMINER",
  MODERATOR = "MODERATOR",
  ADMIN = "ADMIN",
}

export enum AiAssistanceType {
  EVALUATION_SUMMARY = "EVALUATION_SUMMARY",
  SIGNAL_EXPLANATION = "SIGNAL_EXPLANATION",
  RUBRIC_ADVISORY = "RUBRIC_ADVISORY",
}

export enum EvaluatorDeviationStatus {
  NORMAL = "NORMAL",
  MODERATE_DEVIATION = "MODERATE_DEVIATION",
  CRITICAL_DEVIATION = "CRITICAL_DEVIATION",
  INSUFFICIENT_DATA = "INSUFFICIENT_DATA",
}

export enum QualityRiskLevel {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum QualityHotspotType {
  EVALUATOR_ANOMALY = "EVALUATOR_ANOMALY",
  QUESTION_DIFFICULTY = "QUESTION_DIFFICULTY",
  SIGNAL_CONCENTRATION = "SIGNAL_CONCENTRATION",
}

export enum ExaminationDocumentType {
  QUESTION_PAPER = "QUESTION_PAPER",
  MARKING_SCHEME = "MARKING_SCHEME",
  ANSWER_SHEET = "ANSWER_SHEET",
  REFERENCE_ANSWER = "REFERENCE_ANSWER",
}

export enum DocumentOcrStatus {
  PENDING = "PENDING",
  EXTRACTED = "EXTRACTED",
  HUMAN_VERIFIED = "HUMAN_VERIFIED",
  FAILED = "FAILED",
  MANUAL_FALLBACK = "MANUAL_FALLBACK",
}

export enum AnswerVerificationStatus {
  UNVERIFIED = "UNVERIFIED",
  HUMAN_CONFIRMED = "HUMAN_CONFIRMED",
  MANUALLY_EDITED = "MANUALLY_EDITED",
}

export enum AiDisagreementCategory {
  OCR_ERROR = "OCR_ERROR",
  MISSED_VALID_CONCEPT = "MISSED_VALID_CONCEPT",
  RUBRIC_MISMATCH = "RUBRIC_MISMATCH",
  SCORE_INAPPROPRIATE = "SCORE_INAPPROPRIATE",
  INCORRECT_REASONING = "INCORRECT_REASONING",
  INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE",
  AMBIGUOUS_ANSWER = "AMBIGUOUS_ANSWER",
  OTHER = "OTHER",
}
