/**
 * QualitySignal Aggregate Root.
 * Represents a derived quality observation/evidence object generated by an approved detector.
 * Conforms to:
 * - docs/contracts/05-domain-contract.md §7.1, §19-21 (QualitySignal Aggregate)
 * - docs/contracts/06-api-contract.md §25-27, §65 (QualitySignal schema & authority boundary)
 * - docs/contracts/08-data-contract.md §17-18 (QualitySignal persistence & provenance)
 *
 * Invariants:
 * - Strictly an observation/evidence/provenance object.
 * - Must NOT become a finding, misconduct judgment, moderation decision, or AI authority.
 */

import { randomUUID } from "node:crypto";
import { SignalSeverity, QualitySignalStatus } from "@osm/shared";
import type { DetectorProvenance } from "@osm/shared";
import { InvalidArgumentError, InvalidStateTransitionError } from "../errors.js";

export { SignalSeverity, QualitySignalStatus };
export type { DetectorProvenance };

export interface QualitySignalProps {
  id?: string;
  evaluationId: string;
  evaluationVersion: number;
  signalType: string;
  severity: SignalSeverity;
  status?: QualitySignalStatus;
  summary: string;
  evidence: Record<string, unknown>;
  detector: DetectorProvenance;
  createdAt?: string;
  updatedAt?: string;
}

export class QualitySignal {
  readonly id: string;
  readonly evaluationId: string;
  readonly evaluationVersion: number;
  readonly signalType: string;
  readonly severity: SignalSeverity;
  private _status: QualitySignalStatus;
  readonly summary: string;
  readonly evidence: Record<string, unknown>;
  readonly detector: DetectorProvenance;
  readonly createdAt: string;
  private _updatedAt: string;

  private constructor(props: {
    id: string;
    evaluationId: string;
    evaluationVersion: number;
    signalType: string;
    severity: SignalSeverity;
    status: QualitySignalStatus;
    summary: string;
    evidence: Record<string, unknown>;
    detector: DetectorProvenance;
    createdAt: string;
    updatedAt: string;
  }) {
    this.id = props.id;
    this.evaluationId = props.evaluationId;
    this.evaluationVersion = props.evaluationVersion;
    this.signalType = props.signalType;
    this.severity = props.severity;
    this._status = props.status;
    this.summary = props.summary;
    this.evidence = props.evidence;
    this.detector = props.detector;
    this.createdAt = props.createdAt;
    this._updatedAt = props.updatedAt;
  }

  static create(props: QualitySignalProps): QualitySignal {
    if (!props.evaluationId?.trim()) {
      throw new InvalidArgumentError("Evaluation ID is required for QualitySignal.");
    }
    if (props.evaluationVersion === undefined || props.evaluationVersion < 0) {
      throw new InvalidArgumentError("Evaluation version must be a non-negative integer.");
    }
    if (!props.signalType?.trim()) {
      throw new InvalidArgumentError("Signal type is required for QualitySignal.");
    }
    if (!props.summary?.trim()) {
      throw new InvalidArgumentError("Summary is required for QualitySignal.");
    }
    if (!props.detector?.name?.trim() || !props.detector?.version?.trim()) {
      throw new InvalidArgumentError("Detector provenance (name and version) is required.");
    }
    if (!props.severity || !Object.values(SignalSeverity).includes(props.severity)) {
      throw new InvalidArgumentError(`Invalid signal severity: ${props.severity}`);
    }

    const now = new Date().toISOString();
    return new QualitySignal({
      id: props.id?.trim() || randomUUID(),
      evaluationId: props.evaluationId.trim(),
      evaluationVersion: props.evaluationVersion,
      signalType: props.signalType.trim(),
      severity: props.severity,
      status: props.status ?? QualitySignalStatus.REVIEWABLE,
      summary: props.summary.trim(),
      evidence: props.evidence ? { ...props.evidence } : {},
      detector: {
        type: props.detector.type,
        name: props.detector.name.trim(),
        version: props.detector.version.trim(),
        config: props.detector.config ? { ...props.detector.config } : undefined,
      },
      createdAt: props.createdAt ?? now,
      updatedAt: props.updatedAt ?? now,
    });
  }

  static reconstitute(props: {
    id: string;
    evaluationId: string;
    evaluationVersion: number;
    signalType: string;
    severity: SignalSeverity;
    status: QualitySignalStatus;
    summary: string;
    evidence: Record<string, unknown>;
    detector: DetectorProvenance;
    createdAt: string;
    updatedAt: string;
  }): QualitySignal {
    return new QualitySignal(props);
  }

  get status(): QualitySignalStatus {
    return this._status;
  }

  get updatedAt(): string {
    return this._updatedAt;
  }

  linkToCase(caseId: string): void {
    if (this._status !== QualitySignalStatus.REVIEWABLE && this._status !== QualitySignalStatus.GENERATED) {
      throw new InvalidStateTransitionError(
        "QualitySignal",
        this._status,
        QualitySignalStatus.LINKED_TO_CASE
      );
    }
    this._status = QualitySignalStatus.LINKED_TO_CASE;
    this._updatedAt = new Date().toISOString();
    (this.evidence as Record<string, unknown>).linkedCaseId = caseId;
  }

  dismiss(reason?: string): void {
    if (this._status === QualitySignalStatus.RESOLVED) {
      throw new InvalidStateTransitionError(
        "QualitySignal",
        this._status,
        QualitySignalStatus.DISMISSED
      );
    }
    this._status = QualitySignalStatus.DISMISSED;
    this._updatedAt = new Date().toISOString();
    if (reason) {
      (this.evidence as Record<string, unknown>).dismissalReason = reason;
    }
  }

  resolve(outcome?: string): void {
    this._status = QualitySignalStatus.RESOLVED;
    this._updatedAt = new Date().toISOString();
    if (outcome) {
      (this.evidence as Record<string, unknown>).resolutionOutcome = outcome;
    }
  }

  toJSON(): Record<string, unknown> {
    return {
      id: this.id,
      evaluationId: this.evaluationId,
      evaluationVersion: this.evaluationVersion,
      signalType: this.signalType,
      severity: this.severity,
      status: this._status,
      summary: this.summary,
      evidence: this.evidence,
      detector: this.detector,
      createdAt: this.createdAt,
      updatedAt: this._updatedAt,
    };
  }
}
